trigger:
  branches:
    include:
    - main
  tags:
    include:
    - v*

pool:
  vmImage: windows-latest

steps:
- template: templates/package_extension.yml

- publish: $(System.DefaultWorkingDirectory)/minecraft-debugger-js.vsix